DEPLOYMENT_ID = "49146be9-c3cc-4d04-b6e6-a4052c383383"
MODEL_ID = "5f29fe1e-73ca-4e2f-9884-c17c6a56825b"
INSTANCE_ID = "453d97f8-5fd2-4a2e-addc-ad1e8cc68312"
URL = "https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/{}/published_models/{}/deployments/{}/online".format(INSTANCE_ID, MODEL_ID, DEPLOYMENT_ID)
TOKEN = "eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnRJZCI6IjQ1M2Q5N2Y4LTVmZDItNGEyZS1hZGRjLWFkMWU4Y2M2ODMxMiIsImluc3RhbmNlSWQiOiI0NTNkOTdmOC01ZmQyLTRhMmUtYWRkYy1hZDFlOGNjNjgzMTIiLCJwbGFuSWQiOiIzZjZhY2Y0My1lZGU4LTQxM2EtYWM2OS1mOGFmM2JiMGNiZmUiLCJyZWdpb24iOiJldS1nYiIsInVzZXJJZCI6IjkwNDMzNDE1LTg3MjEtNDZlNy05NjUxLTliMjI4YWFmZmRlNSIsImlzcyI6Imh0dHBzOi8vZXUtZ2IubWwuY2xvdWQuaWJtLmNvbS92My9pZGVudGl0eSIsImlhdCI6MTUzMzMwMjM4MiwiZXhwIjoxNTMzMzMxMTgyfQ.fX87WZ6jUp7L9EYeJmdOakAO9xiJOksA7vewolV2u_T-c06wG8Sgy8OP8G8KO8703H4E5shwRNvCzBWPARTIq4eglyFCIyr43lW321bzfjpC_RrQw8vRsr_TbBANwWCbZYK8kN5p8kv_oGGhWG2uTfmod1JS_3ubiUTrpzmHz5iRS4cxyMTowAjJeOLe06acAySlhZGNJ3vAJ1rceGSI0ufM0kF6TKguGrao8dW-LoblcQg5tg__XPzTZTiVGuMZ8LICmOMHfinh5OA9916CkeJb2GFsW23vZDWpjmBhqaMzuAhQ6pk8wsDmpv9fP_TBctDhuN85Ep9nOUaPbjGpaQ"
CHURNED_DATA = {'2U': {'concern': 56,
  'cummulative_health': 221,
  'finance': 66,
  'number_of_checkins': 22,
  'quality': 53,
  'resource': 46},
 'Abode, Inc. d/b/a Moved': {'concern': 85,
  'cummulative_health': 344,
  'finance': 87,
  'number_of_checkins': 29,
  'quality': 85,
  'resource': 87},
 'Acumen Fund, Inc.': {'concern': 28,
  'cummulative_health': 118,
  'finance': 30,
  'number_of_checkins': 10,
  'quality': 30,
  'resource': 30},
 'Affinity': {'concern': 6,
  'cummulative_health': 19,
  'finance': 6,
  'number_of_checkins': 2,
  'quality': 2,
  'resource': 5},
 'Ainsly Limited (DBA Waldo)': {'concern': 30,
  'cummulative_health': 184,
  'finance': 46,
  'number_of_checkins': 18,
  'quality': 54,
  'resource': 54},
 'Alchemy IoT Inc.': {'concern': 88,
  'cummulative_health': 394,
  'finance': 102,
  'number_of_checkins': 34,
  'quality': 102,
  'resource': 102},
 'Allan Gray': {'concern': 70,
  'cummulative_health': 286,
  'finance': 72,
  'number_of_checkins': 24,
  'quality': 72,
  'resource': 72},
 'AlphaSights': {'concern': 61,
  'cummulative_health': 253,
  'finance': 66,
  'number_of_checkins': 22,
  'quality': 61,
  'resource': 65},
 'Angaza': {'concern': 42,
  'cummulative_health': 163,
  'finance': 42,
  'number_of_checkins': 14,
  'quality': 37,
  'resource': 42},
 'AppThis': {'concern': 9,
  'cummulative_health': 72,
  'finance': 21,
  'number_of_checkins': 7,
  'quality': 21,
  'resource': 21},
 'Ascent': {'concern': 36,
  'cummulative_health': 144,
  'finance': 36,
  'number_of_checkins': 12,
  'quality': 36,
  'resource': 36},
 'Asset-Map': {'concern': 57,
  'cummulative_health': 228,
  'finance': 57,
  'number_of_checkins': 19,
  'quality': 57,
  'resource': 57},
 'Assist Inc': {'concern': 16,
  'cummulative_health': 64,
  'finance': 18,
  'number_of_checkins': 6,
  'quality': 14,
  'resource': 16},
 'Atlas': {'concern': 50,
  'cummulative_health': 240,
  'finance': 51,
  'number_of_checkins': 24,
  'quality': 72,
  'resource': 67},
 'Atlas Unlimited, Inc.': {'concern': 57,
  'cummulative_health': 228,
  'finance': 57,
  'number_of_checkins': 19,
  'quality': 57,
  'resource': 57},
 'Attune Insurance Services, LLC': {'concern': 6,
  'cummulative_health': 23,
  'finance': 6,
  'number_of_checkins': 2,
  'quality': 6,
  'resource': 5},
 'Bark & Co.': {'concern': 89,
  'cummulative_health': 338,
  'finance': 93,
  'number_of_checkins': 31,
  'quality': 71,
  'resource': 85},
 'Beam': {'concern': 60,
  'cummulative_health': 243,
  'finance': 63,
  'number_of_checkins': 21,
  'quality': 63,
  'resource': 57},
 'Bluescape': {'concern': 18,
  'cummulative_health': 77,
  'finance': 21,
  'number_of_checkins': 7,
  'quality': 17,
  'resource': 21},
 'Boatflex': {'concern': 73,
  'cummulative_health': 296,
  'finance': 76,
  'number_of_checkins': 27,
  'quality': 73,
  'resource': 74},
 'Bombas': {'concern': 42,
  'cummulative_health': 171,
  'finance': 51,
  'number_of_checkins': 17,
  'quality': 37,
  'resource': 41},
 'Bombfell': {'concern': 9,
  'cummulative_health': 36,
  'finance': 9,
  'number_of_checkins': 3,
  'quality': 9,
  'resource': 9},
 'Brickwork': {'concern': 78,
  'cummulative_health': 321,
  'finance': 81,
  'number_of_checkins': 27,
  'quality': 81,
  'resource': 81},
 'Bright Hive': {'concern': 61,
  'cummulative_health': 206,
  'finance': 22,
  'number_of_checkins': 21,
  'quality': 62,
  'resource': 61},
 'Brightwheel': {'concern': 35,
  'cummulative_health': 129,
  'finance': 39,
  'number_of_checkins': 13,
  'quality': 25,
  'resource': 30},
 'BuffaloGrid Ltd': {'concern': 69,
  'cummulative_health': 247,
  'finance': 50,
  'number_of_checkins': 28,
  'quality': 57,
  'resource': 71},
 'CareerVillage.org': {'concern': 5,
  'cummulative_health': 22,
  'finance': 6,
  'number_of_checkins': 2,
  'quality': 6,
  'resource': 5},
 'Case Commons': {'concern': 37,
  'cummulative_health': 161,
  'finance': 42,
  'number_of_checkins': 14,
  'quality': 40,
  'resource': 42},
 'Ceros': {'concern': 88,
  'cummulative_health': 341,
  'finance': 90,
  'number_of_checkins': 30,
  'quality': 76,
  'resource': 87},
 'Chan Zuckerberg Initiative': {'concern': 42,
  'cummulative_health': 181,
  'finance': 45,
  'number_of_checkins': 16,
  'quality': 48,
  'resource': 46},
 'Chewse': {'concern': 63,
  'cummulative_health': 247,
  'finance': 63,
  'number_of_checkins': 21,
  'quality': 59,
  'resource': 62},
 'CircleLink Health': {'concern': 26,
  'cummulative_health': 107,
  'finance': 30,
  'number_of_checkins': 10,
  'quality': 21,
  'resource': 30},
 'Civic Technologies, Inc.': {'concern': 16,
  'cummulative_health': 63,
  'finance': 19,
  'number_of_checkins': 7,
  'quality': 14,
  'resource': 14},
 'CleanChoice Energy Shared Services, LLC': {'concern': 36,
  'cummulative_health': 136,
  'finance': 36,
  'number_of_checkins': 12,
  'quality': 29,
  'resource': 35},
 'Cloudflare': {'concern': 33,
  'cummulative_health': 130,
  'finance': 33,
  'number_of_checkins': 11,
  'quality': 31,
  'resource': 33},
 'Clovi Corporation': {'concern': 42,
  'cummulative_health': 168,
  'finance': 42,
  'number_of_checkins': 14,
  'quality': 42,
  'resource': 42},
 'CoEdition': {'concern': 42,
  'cummulative_health': 168,
  'finance': 42,
  'number_of_checkins': 14,
  'quality': 42,
  'resource': 42},
 'Cobalt Robotics': {'concern': 69,
  'cummulative_health': 281,
  'finance': 72,
  'number_of_checkins': 24,
  'quality': 69,
  'resource': 71},
 'CodeStream': {'concern': 24,
  'cummulative_health': 101,
  'finance': 27,
  'number_of_checkins': 9,
  'quality': 23,
  'resource': 27},
 'Codeverse': {'concern': 40,
  'cummulative_health': 165,
  'finance': 42,
  'number_of_checkins': 14,
  'quality': 41,
  'resource': 42},
 'CoinMetro Group': {'concern': 78,
  'cummulative_health': 291,
  'finance': 84,
  'number_of_checkins': 28,
  'quality': 67,
  'resource': 62},
 'CommonBond': {'concern': 69,
  'cummulative_health': 276,
  'finance': 69,
  'number_of_checkins': 23,
  'quality': 69,
  'resource': 69},
 'Conqa': {'concern': 30,
  'cummulative_health': 123,
  'finance': 31,
  'number_of_checkins': 11,
  'quality': 31,
  'resource': 31},
 'Coursera': {'concern': 6,
  'cummulative_health': 24,
  'finance': 6,
  'number_of_checkins': 2,
  'quality': 6,
  'resource': 6},
 'Cratejoy': {'concern': 28,
  'cummulative_health': 139,
  'finance': 39,
  'number_of_checkins': 13,
  'quality': 33,
  'resource': 39},
 'CrunchBase': {'concern': 14,
  'cummulative_health': 83,
  'finance': 24,
  'number_of_checkins': 8,
  'quality': 21,
  'resource': 24},
 'DMX Solutions PR LLC': {'concern': 12,
  'cummulative_health': 51,
  'finance': 15,
  'number_of_checkins': 5,
  'quality': 11,
  'resource': 13},
 'Daily Muse Inc': {'concern': 32,
  'cummulative_health': 176,
  'finance': 48,
  'number_of_checkins': 16,
  'quality': 48,
  'resource': 48},
 'Dirty Lemon Beverages LLC': {'concern': 12,
  'cummulative_health': 48,
  'finance': 12,
  'number_of_checkins': 4,
  'quality': 12,
  'resource': 12},
 'Dopamine Labs': {'concern': 75,
  'cummulative_health': 296,
  'finance': 71,
  'number_of_checkins': 25,
  'quality': 75,
  'resource': 75},
 'Elliot.': {'concern': 18,
  'cummulative_health': 108,
  'finance': 30,
  'number_of_checkins': 10,
  'quality': 30,
  'resource': 30},
 'Embark': {'concern': 12,
  'cummulative_health': 74,
  'finance': 21,
  'number_of_checkins': 7,
  'quality': 20,
  'resource': 21},
 'Enuma, Inc.': {'concern': 75,
  'cummulative_health': 299,
  'finance': 75,
  'number_of_checkins': 25,
  'quality': 75,
  'resource': 74},
 'Ethfinex Inc.': {'concern': 9,
  'cummulative_health': 47,
  'finance': 21,
  'number_of_checkins': 7,
  'quality': 8,
  'resource': 9},
 'Everplans': {'concern': 63,
  'cummulative_health': 252,
  'finance': 63,
  'number_of_checkins': 21,
  'quality': 63,
  'resource': 63},
 'EveryLayer Inc.': {'concern': 102,
  'cummulative_health': 400,
  'finance': 102,
  'number_of_checkins': 34,
  'quality': 101,
  'resource': 95},
 'ExecOnline': {'concern': 55,
  'cummulative_health': 244,
  'finance': 63,
  'number_of_checkins': 21,
  'quality': 63,
  'resource': 63},
 'ExemptMeNow': {'concern': 35,
  'cummulative_health': 110,
  'finance': 27,
  'number_of_checkins': 12,
  'quality': 30,
  'resource': 18},
 'FarmLogs': {'concern': 39,
  'cummulative_health': 144,
  'finance': 39,
  'number_of_checkins': 13,
  'quality': 27,
  'resource': 39},
 'Fathom': {'concern': 57,
  'cummulative_health': 314,
  'finance': 83,
  'number_of_checkins': 29,
  'quality': 87,
  'resource': 87},
 'FaunaDB': {'concern': 22,
  'cummulative_health': 109,
  'finance': 30,
  'number_of_checkins': 10,
  'quality': 29,
  'resource': 28},
 'Finhaven': {'concern': 27,
  'cummulative_health': 149,
  'finance': 42,
  'number_of_checkins': 14,
  'quality': 42,
  'resource': 38},
 'Firepoint Solutions': {'concern': 46,
  'cummulative_health': 207,
  'finance': 57,
  'number_of_checkins': 19,
  'quality': 47,
  'resource': 57},
 'First Access, Inc.': {'concern': 69,
  'cummulative_health': 291,
  'finance': 84,
  'number_of_checkins': 28,
  'quality': 62,
  'resource': 76},
 'FiveStars': {'concern': 18,
  'cummulative_health': 72,
  'finance': 18,
  'number_of_checkins': 6,
  'quality': 18,
  'resource': 18},
 'FlightOffice': {'concern': 72,
  'cummulative_health': 260,
  'finance': 52,
  'number_of_checkins': 24,
  'quality': 64,
  'resource': 72},
 'Forcefield Online, Inc.': {'concern': 47,
  'cummulative_health': 181,
  'finance': 51,
  'number_of_checkins': 17,
  'quality': 41,
  'resource': 42},
 'Fractured Atlas': {'concern': 74,
  'cummulative_health': 293,
  'finance': 75,
  'number_of_checkins': 25,
  'quality': 69,
  'resource': 75},
 'Fuzzy Pet Health': {'concern': 2,
  'cummulative_health': 20,
  'finance': 6,
  'number_of_checkins': 2,
  'quality': 6,
  'resource': 6},
 'Genius Of And': {'concern': 23,
  'cummulative_health': 120,
  'finance': 31,
  'number_of_checkins': 11,
  'quality': 33,
  'resource': 33},
 'Genoa Telepsychiatry': {'concern': 23,
  'cummulative_health': 112,
  'finance': 29,
  'number_of_checkins': 10,
  'quality': 30,
  'resource': 30},
 'GitHub': {'concern': 66,
  'cummulative_health': 273,
  'finance': 69,
  'number_of_checkins': 23,
  'quality': 69,
  'resource': 69},
 'Gobble': {'concern': 76,
  'cummulative_health': 327,
  'finance': 87,
  'number_of_checkins': 29,
  'quality': 77,
  'resource': 87},
 'Gokash': {'concern': 47,
  'cummulative_health': 172,
  'finance': 27,
  'number_of_checkins': 17,
  'quality': 51,
  'resource': 47},
 'Golden Era Club Limited': {'concern': 3,
  'cummulative_health': 12,
  'finance': 3,
  'number_of_checkins': 1,
  'quality': 3,
  'resource': 3},
 'Grain': {'concern': 30,
  'cummulative_health': 131,
  'finance': 29,
  'number_of_checkins': 12,
  'quality': 36,
  'resource': 36},
 'Groove Labs': {'concern': 66,
  'cummulative_health': 261,
  'finance': 69,
  'number_of_checkins': 23,
  'quality': 62,
  'resource': 64},
 'GroupBookers, Inc., DBA OfficeNinjas': {'concern': 9,
  'cummulative_health': 36,
  'finance': 9,
  'number_of_checkins': 3,
  'quality': 9,
  'resource': 9},
 'Gruntwork': {'concern': 61,
  'cummulative_health': 249,
  'finance': 63,
  'number_of_checkins': 21,
  'quality': 63,
  'resource': 62},
 'Guesty Inc.': {'concern': 25,
  'cummulative_health': 113,
  'finance': 33,
  'number_of_checkins': 11,
  'quality': 25,
  'resource': 30},
 'Gusto': {'concern': 60,
  'cummulative_health': 240,
  'finance': 60,
  'number_of_checkins': 20,
  'quality': 60,
  'resource': 60},
 'Hazel Analytics, Inc.': {'concern': 28,
  'cummulative_health': 126,
  'finance': 36,
  'number_of_checkins': 12,
  'quality': 26,
  'resource': 36},
 'Headspace': {'concern': 60,
  'cummulative_health': 249,
  'finance': 63,
  'number_of_checkins': 21,
  'quality': 63,
  'resource': 63},
 'HingeTo': {'concern': 72,
  'cummulative_health': 283,
  'finance': 72,
  'number_of_checkins': 24,
  'quality': 67,
  'resource': 72},
 'Homie Inc.': {'concern': 72,
  'cummulative_health': 276,
  'finance': 72,
  'number_of_checkins': 24,
  'quality': 63,
  'resource': 69},
 'I&M Bank Ltd': {'concern': 27,
  'cummulative_health': 126,
  'finance': 33,
  'number_of_checkins': 11,
  'quality': 33,
  'resource': 33},
 'InVisionApp': {'concern': 74,
  'cummulative_health': 319,
  'finance': 90,
  'number_of_checkins': 30,
  'quality': 77,
  'resource': 78},
 'Industrious': {'concern': 61,
  'cummulative_health': 323,
  'finance': 82,
  'number_of_checkins': 31,
  'quality': 93,
  'resource': 87},
 'Influence & Co.': {'concern': 36,
  'cummulative_health': 175,
  'finance': 47,
  'number_of_checkins': 16,
  'quality': 44,
  'resource': 48},
 'InquisitHealth': {'concern': 53,
  'cummulative_health': 218,
  'finance': 57,
  'number_of_checkins': 19,
  'quality': 51,
  'resource': 57},
 'Insurance Zebra, Inc.': {'concern': 73,
  'cummulative_health': 260,
  'finance': 75,
  'number_of_checkins': 25,
  'quality': 58,
  'resource': 54},
 'Integral Agile Inc.': {'concern': 86,
  'cummulative_health': 350,
  'finance': 90,
  'number_of_checkins': 30,
  'quality': 84,
  'resource': 90},
 'Jetpack': {'concern': 15,
  'cummulative_health': 60,
  'finance': 15,
  'number_of_checkins': 5,
  'quality': 15,
  'resource': 15},
 'Journeyfront': {'concern': 12,
  'cummulative_health': 48,
  'finance': 12,
  'number_of_checkins': 4,
  'quality': 12,
  'resource': 12},
 'Jumpcut': {'concern': 31,
  'cummulative_health': 127,
  'finance': 33,
  'number_of_checkins': 11,
  'quality': 30,
  'resource': 33},
 'Juntos': {'concern': 66,
  'cummulative_health': 257,
  'finance': 66,
  'number_of_checkins': 22,
  'quality': 65,
  'resource': 60},
 'KickBack Apps': {'concern': 49,
  'cummulative_health': 236,
  'finance': 48,
  'number_of_checkins': 24,
  'quality': 72,
  'resource': 67},
 'Kind Foundation, Inc. (aka Empatico)': {'concern': 78,
  'cummulative_health': 310,
  'finance': 78,
  'number_of_checkins': 26,
  'quality': 78,
  'resource': 76},
 'LUMA Institute': {'concern': 30,
  'cummulative_health': 128,
  'finance': 36,
  'number_of_checkins': 12,
  'quality': 31,
  'resource': 31},
 'LawTrades': {'concern': 36,
  'cummulative_health': 141,
  'finance': 36,
  'number_of_checkins': 12,
  'quality': 33,
  'resource': 36},
 'Layer': {'concern': 3,
  'cummulative_health': 25,
  'finance': 9,
  'number_of_checkins': 3,
  'quality': 6,
  'resource': 7},
 'Leap Forward': {'concern': 45,
  'cummulative_health': 243,
  'finance': 66,
  'number_of_checkins': 22,
  'quality': 66,
  'resource': 66},
 'LemonStand': {'concern': 13,
  'cummulative_health': 77,
  'finance': 24,
  'number_of_checkins': 8,
  'quality': 19,
  'resource': 21},
 'Lessonly': {'concern': 69,
  'cummulative_health': 276,
  'finance': 69,
  'number_of_checkins': 23,
  'quality': 69,
  'resource': 69},
 'LevelTen Energy': {'concern': 63,
  'cummulative_health': 252,
  'finance': 63,
  'number_of_checkins': 21,
  'quality': 63,
  'resource': 63},
 'Lex Machina': {'concern': 21,
  'cummulative_health': 84,
  'finance': 21,
  'number_of_checkins': 7,
  'quality': 21,
  'resource': 21},
 'Loyyal': {'concern': 23,
  'cummulative_health': 106,
  'finance': 33,
  'number_of_checkins': 11,
  'quality': 25,
  'resource': 25},
 'MIXhalo': {'concern': 102,
  'cummulative_health': 421,
  'finance': 108,
  'number_of_checkins': 36,
  'quality': 108,
  'resource': 103},
 'Makook': {'concern': 24,
  'cummulative_health': 96,
  'finance': 24,
  'number_of_checkins': 8,
  'quality': 24,
  'resource': 24},
 'Mason': {'concern': 78,
  'cummulative_health': 300,
  'finance': 90,
  'number_of_checkins': 30,
  'quality': 74,
  'resource': 58},
 'MassChallenge, Inc.': {'concern': 3,
  'cummulative_health': 12,
  'finance': 3,
  'number_of_checkins': 1,
  'quality': 3,
  'resource': 3},
 'Mastercard': {'concern': 66,
  'cummulative_health': 244,
  'finance': 32,
  'number_of_checkins': 25,
  'quality': 75,
  'resource': 71},
 'Maven Machines, Inc.': {'concern': 73,
  'cummulative_health': 289,
  'finance': 75,
  'number_of_checkins': 25,
  'quality': 66,
  'resource': 75},
 'Medsender': {'concern': 57,
  'cummulative_health': 228,
  'finance': 57,
  'number_of_checkins': 19,
  'quality': 57,
  'resource': 57},
 'MightyHive': {'concern': 51,
  'cummulative_health': 204,
  'finance': 51,
  'number_of_checkins': 17,
  'quality': 51,
  'resource': 51},
 'Migo': {'concern': 7,
  'cummulative_health': 47,
  'finance': 15,
  'number_of_checkins': 5,
  'quality': 10,
  'resource': 15},
 'MindRight Inc.': {'concern': 42,
  'cummulative_health': 168,
  'finance': 42,
  'number_of_checkins': 14,
  'quality': 42,
  'resource': 42},
 'Mix.com': {'concern': 80,
  'cummulative_health': 344,
  'finance': 93,
  'number_of_checkins': 31,
  'quality': 83,
  'resource': 88},
 'Mobiliti, LLC': {'concern': 18,
  'cummulative_health': 71,
  'finance': 18,
  'number_of_checkins': 6,
  'quality': 17,
  'resource': 18},
 'Motherly Media, Inc.': {'concern': 76,
  'cummulative_health': 388,
  'finance': 103,
  'number_of_checkins': 35,
  'quality': 105,
  'resource': 104},
 'Multichoice Support Services ( Pry) Ltd': {'concern': 21,
  'cummulative_health': 82,
  'finance': 19,
  'number_of_checkins': 7,
  'quality': 21,
  'resource': 21},
 'NY Academy of Sciences': {'concern': 24,
  'cummulative_health': 126,
  'finance': 39,
  'number_of_checkins': 13,
  'quality': 32,
  'resource': 31},
 'Namely, Inc.': {'concern': 48,
  'cummulative_health': 192,
  'finance': 48,
  'number_of_checkins': 16,
  'quality': 48,
  'resource': 48},
 'Needle': {'concern': 69,
  'cummulative_health': 276,
  'finance': 67,
  'number_of_checkins': 24,
  'quality': 72,
  'resource': 68},
 'Nesterly, Inc.': {'concern': 27,
  'cummulative_health': 108,
  'finance': 27,
  'number_of_checkins': 9,
  'quality': 27,
  'resource': 27},
 'Nexporter Limited': {'concern': 30,
  'cummulative_health': 205,
  'finance': 46,
  'number_of_checkins': 23,
  'quality': 69,
  'resource': 60},
 'NiJeL': {'concern': 48,
  'cummulative_health': 180,
  'finance': 24,
  'number_of_checkins': 18,
  'quality': 54,
  'resource': 54},
 'Nivi Inc.': {'concern': 63,
  'cummulative_health': 261,
  'finance': 66,
  'number_of_checkins': 23,
  'quality': 69,
  'resource': 63},
 'Nomad Interactive LLC': {'concern': 43,
  'cummulative_health': 185,
  'finance': 49,
  'number_of_checkins': 18,
  'quality': 53,
  'resource': 40},
 'Omise Co., Ltd.': {'concern': 7,
  'cummulative_health': 34,
  'finance': 9,
  'number_of_checkins': 3,
  'quality': 9,
  'resource': 9},
 'OnePitch LLC': {'concern': 63,
  'cummulative_health': 252,
  'finance': 63,
  'number_of_checkins': 21,
  'quality': 63,
  'resource': 63},
 'Open Garden Inc.': {'concern': 51,
  'cummulative_health': 204,
  'finance': 51,
  'number_of_checkins': 17,
  'quality': 51,
  'resource': 51},
 'OpenFan': {'concern': 34,
  'cummulative_health': 140,
  'finance': 33,
  'number_of_checkins': 13,
  'quality': 36,
  'resource': 37},
 'Opendoor': {'concern': 56,
  'cummulative_health': 244,
  'finance': 66,
  'number_of_checkins': 22,
  'quality': 56,
  'resource': 66},
 'Osmosis Interactive, Inc': {'concern': 36,
  'cummulative_health': 144,
  'finance': 36,
  'number_of_checkins': 12,
  'quality': 36,
  'resource': 36},
 'Overview': {'concern': 38,
  'cummulative_health': 154,
  'finance': 39,
  'number_of_checkins': 13,
  'quality': 38,
  'resource': 39},
 'Owlet Baby Care': {'concern': 76,
  'cummulative_health': 335,
  'finance': 87,
  'number_of_checkins': 29,
  'quality': 87,
  'resource': 85},
 'Partners in Health': {'concern': 9,
  'cummulative_health': 36,
  'finance': 9,
  'number_of_checkins': 3,
  'quality': 9,
  'resource': 9},
 'Phosphorus': {'concern': 8,
  'cummulative_health': 44,
  'finance': 12,
  'number_of_checkins': 4,
  'quality': 12,
  'resource': 12},
 'Pine Valley LLC': {'concern': 74,
  'cummulative_health': 302,
  'finance': 78,
  'number_of_checkins': 26,
  'quality': 76,
  'resource': 74},
 'Planview': {'concern': 66,
  'cummulative_health': 264,
  'finance': 66,
  'number_of_checkins': 22,
  'quality': 66,
  'resource': 66},
 'Pluralsight, LLC': {'concern': 63,
  'cummulative_health': 243,
  'finance': 61,
  'number_of_checkins': 21,
  'quality': 63,
  'resource': 56},
 'Pluto': {'concern': 58,
  'cummulative_health': 271,
  'finance': 84,
  'number_of_checkins': 28,
  'quality': 78,
  'resource': 51},
 'Pretty Instant, Inc.': {'concern': 50,
  'cummulative_health': 216,
  'finance': 58,
  'number_of_checkins': 20,
  'quality': 50,
  'resource': 58},
 'RTI International': {'concern': 39,
  'cummulative_health': 156,
  'finance': 39,
  'number_of_checkins': 13,
  'quality': 39,
  'resource': 39},
 'Ragnar Events, LLC': {'concern': 24,
  'cummulative_health': 96,
  'finance': 24,
  'number_of_checkins': 8,
  'quality': 24,
  'resource': 24},
 'Rainforest QA': {'concern': 44,
  'cummulative_health': 194,
  'finance': 54,
  'number_of_checkins': 18,
  'quality': 48,
  'resource': 48},
 'Raise': {'concern': 57,
  'cummulative_health': 264,
  'finance': 69,
  'number_of_checkins': 23,
  'quality': 69,
  'resource': 69},
 'Reaction Commerce, Inc.': {'concern': 59,
  'cummulative_health': 237,
  'finance': 60,
  'number_of_checkins': 20,
  'quality': 58,
  'resource': 60},
 'Reed Professional Services, LLC': {'concern': 77,
  'cummulative_health': 306,
  'finance': 78,
  'number_of_checkins': 26,
  'quality': 78,
  'resource': 73},
 'Relish Careers': {'concern': 49,
  'cummulative_health': 219,
  'finance': 63,
  'number_of_checkins': 21,
  'quality': 56,
  'resource': 51},
 'Rentgrata, Inc.': {'concern': 12,
  'cummulative_health': 48,
  'finance': 12,
  'number_of_checkins': 4,
  'quality': 12,
  'resource': 12},
 'Restaurant Brands International': {'concern': 61,
  'cummulative_health': 324,
  'finance': 93,
  'number_of_checkins': 31,
  'quality': 91,
  'resource': 79},
 'Roam': {'concern': 35,
  'cummulative_health': 144,
  'finance': 35,
  'number_of_checkins': 13,
  'quality': 37,
  'resource': 37},
 'STORD LLC': {'concern': 43,
  'cummulative_health': 196,
  'finance': 51,
  'number_of_checkins': 17,
  'quality': 51,
  'resource': 51},
 'Safaricom': {'concern': 31,
  'cummulative_health': 145,
  'finance': 36,
  'number_of_checkins': 15,
  'quality': 35,
  'resource': 43},
 'Saucey': {'concern': 56,
  'cummulative_health': 226,
  'finance': 57,
  'number_of_checkins': 19,
  'quality': 56,
  'resource': 57},
 'Schoolio Platform Inc.': {'concern': 11,
  'cummulative_health': 47,
  'finance': 12,
  'number_of_checkins': 4,
  'quality': 12,
  'resource': 12},
 'SeatGeek': {'concern': 55,
  'cummulative_health': 253,
  'finance': 78,
  'number_of_checkins': 26,
  'quality': 47,
  'resource': 73},
 'ShopKeep': {'concern': 16,
  'cummulative_health': 68,
  'finance': 18,
  'number_of_checkins': 6,
  'quality': 17,
  'resource': 17},
 'ShowClix': {'concern': 63,
  'cummulative_health': 250,
  'finance': 63,
  'number_of_checkins': 21,
  'quality': 62,
  'resource': 62},
 'Skillshare': {'concern': 75,
  'cummulative_health': 295,
  'finance': 75,
  'number_of_checkins': 25,
  'quality': 70,
  'resource': 75},
 'Solstice Energy Solutions, Inc.': {'concern': 6,
  'cummulative_health': 24,
  'finance': 6,
  'number_of_checkins': 2,
  'quality': 6,
  'resource': 6},
 'SpatialKey': {'concern': 78,
  'cummulative_health': 305,
  'finance': 78,
  'number_of_checkins': 26,
  'quality': 72,
  'resource': 77},
 'Splash': {'concern': 56,
  'cummulative_health': 227,
  'finance': 57,
  'number_of_checkins': 19,
  'quality': 57,
  'resource': 57},
 'Springbuk': {'concern': 60,
  'cummulative_health': 240,
  'finance': 60,
  'number_of_checkins': 20,
  'quality': 60,
  'resource': 60},
 'Starcity Properties, Inc.': {'concern': 42,
  'cummulative_health': 177,
  'finance': 45,
  'number_of_checkins': 15,
  'quality': 45,
  'resource': 45},
 'Stem Disintermedia': {'concern': 33,
  'cummulative_health': 136,
  'finance': 36,
  'number_of_checkins': 12,
  'quality': 33,
  'resource': 34},
 'StudioHop, LLC': {'concern': 57,
  'cummulative_health': 223,
  'finance': 57,
  'number_of_checkins': 19,
  'quality': 57,
  'resource': 52},
 'Syncano': {'concern': 52,
  'cummulative_health': 228,
  'finance': 56,
  'number_of_checkins': 20,
  'quality': 60,
  'resource': 60},
 'System1': {'concern': 9,
  'cummulative_health': 36,
  'finance': 9,
  'number_of_checkins': 3,
  'quality': 9,
  'resource': 9},
 'Taproot Foundation': {'concern': 63,
  'cummulative_health': 240,
  'finance': 63,
  'number_of_checkins': 21,
  'quality': 63,
  'resource': 51},
 'Tastemakers Africa': {'concern': 49,
  'cummulative_health': 257,
  'finance': 58,
  'number_of_checkins': 28,
  'quality': 78,
  'resource': 72},
 'Teamup Sports, Inc.': {'concern': 18,
  'cummulative_health': 80,
  'finance': 24,
  'number_of_checkins': 8,
  'quality': 22,
  'resource': 16},
 'The Guild': {'concern': 41,
  'cummulative_health': 211,
  'finance': 60,
  'number_of_checkins': 20,
  'quality': 50,
  'resource': 60},
 'The Human Diagnosis Project': {'concern': 12,
  'cummulative_health': 87,
  'finance': 30,
  'number_of_checkins': 10,
  'quality': 29,
  'resource': 16},
 'Transfix': {'concern': 70,
  'cummulative_health': 282,
  'finance': 72,
  'number_of_checkins': 24,
  'quality': 72,
  'resource': 68},
 'Two Sigma Investments': {'concern': 65,
  'cummulative_health': 258,
  'finance': 69,
  'number_of_checkins': 23,
  'quality': 60,
  'resource': 64},
 'Unqork Inc': {'concern': 9,
  'cummulative_health': 36,
  'finance': 9,
  'number_of_checkins': 3,
  'quality': 9,
  'resource': 9},
 'Up Advisors LLC  (DBA FYI)': {'concern': 39,
  'cummulative_health': 165,
  'finance': 42,
  'number_of_checkins': 14,
  'quality': 42,
  'resource': 42},
 'Vacayo Inc.': {'concern': 33,
  'cummulative_health': 130,
  'finance': 32,
  'number_of_checkins': 11,
  'quality': 33,
  'resource': 32},
 'Vemba': {'concern': 48,
  'cummulative_health': 191,
  'finance': 48,
  'number_of_checkins': 16,
  'quality': 47,
  'resource': 48},
 'Viacom': {'concern': 88,
  'cummulative_health': 331,
  'finance': 94,
  'number_of_checkins': 32,
  'quality': 70,
  'resource': 79},
 'Vibes': {'concern': 12,
  'cummulative_health': 48,
  'finance': 12,
  'number_of_checkins': 4,
  'quality': 12,
  'resource': 12},
 'Vimala, LLC dba Alecia': {'concern': 39,
  'cummulative_health': 150,
  'finance': 42,
  'number_of_checkins': 14,
  'quality': 36,
  'resource': 33},
 'WEconnect': {'concern': 1,
  'cummulative_health': 10,
  'finance': 3,
  'number_of_checkins': 1,
  'quality': 3,
  'resource': 3},
 'Waldo Photos, Inc.': {'concern': 8,
  'cummulative_health': 32,
  'finance': 9,
  'number_of_checkins': 3,
  'quality': 9,
  'resource': 6},
 'Walker & Company Brands, LLC': {'concern': 25,
  'cummulative_health': 125,
  'finance': 39,
  'number_of_checkins': 13,
  'quality': 26,
  'resource': 35},
 'Weebly': {'concern': 12,
  'cummulative_health': 102,
  'finance': 30,
  'number_of_checkins': 10,
  'quality': 30,
  'resource': 30},
 'Wellio Inc.': {'concern': 66,
  'cummulative_health': 255,
  'finance': 66,
  'number_of_checkins': 22,
  'quality': 60,
  'resource': 63},
 'Whitelabel Co.': {'concern': 7,
  'cummulative_health': 40,
  'finance': 15,
  'number_of_checkins': 5,
  'quality': 5,
  'resource': 13},
 'Women Who Code Inc.': {'concern': 36,
  'cummulative_health': 144,
  'finance': 36,
  'number_of_checkins': 12,
  'quality': 36,
  'resource': 36},
 'Yup Technologies Inc.': {'concern': 1,
  'cummulative_health': 10,
  'finance': 3,
  'number_of_checkins': 1,
  'quality': 3,
  'resource': 3},
 'Zapier': {'concern': 71,
  'cummulative_health': 287,
  'finance': 72,
  'number_of_checkins': 24,
  'quality': 72,
  'resource': 72},
 'Zebra Intelligence': {'concern': 25,
  'cummulative_health': 112,
  'finance': 30,
  'number_of_checkins': 10,
  'quality': 30,
  'resource': 27},
 'Zego, Inc.': {'concern': 21,
  'cummulative_health': 84,
  'finance': 21,
  'number_of_checkins': 7,
  'quality': 21,
  'resource': 21},
 'ZipBooks': {'concern': 4,
  'cummulative_health': 18,
  'finance': 6,
  'number_of_checkins': 2,
  'quality': 4,
  'resource': 4},
 'data.world': {'concern': 51,
  'cummulative_health': 223,
  'finance': 66,
  'number_of_checkins': 22,
  'quality': 45,
  'resource': 61},
 'payoff': {'concern': 59,
  'cummulative_health': 225,
  'finance': 66,
  'number_of_checkins': 22,
  'quality': 46,
  'resource': 54}}